export const URL_GUAJOLOTAS = 'https://guappjolotas-jsonserver.herokuapp.com/guajolotas/'
export const URL_BEBIDAS = 'https://guappjolotas-jsonserver.herokuapp.com/bebidas/'
export const URL_TAMALES = 'https://guappjolotas-jsonserver.herokuapp.com/tamales/'
export const URL_SABORES = 'https://guappjolotas-jsonserver.herokuapp.com/sabores/'
export const URL_SABORES_BEBIDAS = 'https://guappjolotas-jsonserver.herokuapp.com/saboresBebidas/'
export const URL_SEARCH = 'https://guappjolotas-jsonserver.herokuapp.com/allproducts/?type_like='